#!/usr/bin/env bash
# usage: scene_prompt.sh <activity> <frame a-e> -> prints the fixed-template scene prompt
act=$1; frame=$2
case "$act" in
  play) BASE="The woman plays with the cat using a feather wand toy on a stick; the cat is playful and pouncing at the toy.";
        case $frame in a) M="Moment 1: she crouches slightly and dangles the feather toy low; the cat crouches ready to pounce.";; b) M="Moment 2: she swings the feather up; the cat leaps toward it.";; c) M="Moment 3: the cat is mid-air with paws out, she laughs.";; d) M="Moment 4: the cat lands and bats the toy, she keeps it moving.";; e) M="Moment 5: the cat sits happily holding the toy with a paw, she smiles.";; esac; CROP="Full figures, woman's head about 16% of the image height.";;
  educate) BASE="The woman sits on the floor teaching the cat a lesson with a picture card and a small treat; the cat sits attentively facing her.";
        case $frame in a) M="Moment 1: she holds up a picture card; the cat looks at it curiously.";; b) M="Moment 2: she points at the card; the cat tilts its head.";; c) M="Moment 3: the cat raises one paw as if answering.";; d) M="Moment 4: she gives the cat a small treat.";; e) M="Moment 5: the cat sits proudly, she gives a thumbs-up.";; esac; CROP="Full figures, woman's head about 16% of the image height.";;
  groom) BASE="The woman sits and gently brushes the cat with a small brush; the cat sits on a cushion in front of her, eyes closed in comfort.";
        case $frame in a) M="Moment 1: she picks up the brush; the cat sits waiting.";; b) M="Moment 2: she brushes the cat's back.";; c) M="Moment 3: she brushes the cat's cheek; the cat leans in.";; d) M="Moment 4: she wipes the cat's paws with a small cloth.";; e) M="Moment 5: the cat looks glossy and content, she smiles.";; esac; CROP="Medium close framing is allowed: woman's head up to 24% of the image height, still a clear margin.";;
  train) BASE="The woman sits on the floor and trains the cat's obedience with a small treat: the cat practices sit and give-paw on command.";
        case $frame in a) M="Moment 1: she holds up a small treat; the cat sits looking at it.";; b) M="Moment 2: she raises her hand as a signal; the cat stays seated, ears up.";; c) M="Moment 3: the cat lifts one front paw toward her open hand.";; d) M="Moment 4: the cat gives paw and she holds it gently.";; e) M="Moment 5: she gives the treat, the cat sits proudly.";; esac; CROP="Full figures, woman's head about 16% of the image height.";;
  rest) BASE="The cat rests on a round cushion while the woman sits quietly beside it reading a small book.";
        case $frame in a) M="Moment 1: she places a soft blanket near the cushion; the cat yawns.";; b) M="Moment 2: the cat circles the cushion.";; c) M="Moment 3: the cat curls up with half-closed eyes.";; d) M="Moment 4: she reads quietly beside the cat.";; e) M="Moment 5: the cat sleeps peacefully, she smiles at it.";; esac; CROP="Medium close framing is allowed: woman's head up to 24% of the image height, still a clear margin.";;
  outing) BASE="The woman takes the cat for a short outing: the cat wears a small harness with a leash held by her.";
        case $frame in a) M="Moment 1: she fits the harness on the cat.";; b) M="Moment 2: they step forward together, leash loose.";; c) M="Moment 3: they walk side by side.";; d) M="Moment 4: the cat stops to sniff the floor curiously.";; e) M="Moment 5: the cat looks back up at her happily.";; esac; CROP="Full figures, woman's head about 16% of the image height.";;
  job) BASE="The cat works a mouse-catching part-time job: it hunts a toy mouse while the woman stands beside it and watches in every moment, and in the last moment she holds out a small coin pouch to pay it. The woman is visible in every panel, including the first.";
        case $frame in a) M="Moment 1: the cat spots a toy mouse, ears forward; she watches.";; b) M="Moment 2: the cat stalks low toward the mouse.";; c) M="Moment 3: the cat pounces on the toy mouse.";; d) M="Moment 4: the cat proudly holds the toy mouse in its mouth.";; e) M="Moment 5: she hands over a small coin pouch, the cat sits proudly.";; esac; CROP="Full figures, woman's head about 16% of the image height.";;
esac
echo "Create a game scene illustration in clean flat cel-shaded style with uniform medium-thick dark outlines, the same style as the references. The cat must be exactly the cat in the first reference image (identical markings: black head with white blaze, white chest and belly, two large black body patches, black tail, white paws, yellow eyes). The woman must be exactly the girl in the second reference image (long dark brown hair, blue and white striped t-shirt, navy slim pants, white sneakers, gentle smile). Scene: $BASE $M Plain flat warm cream background (#F6EBD9) with only a faint floor line, no other scenery, no text. $CROP At least 5% empty margin on all sides. Square composition."
